single_cycle:	version3.o
	g++ -o single_cycle version3.o
version3.o:	version3.cpp
	g++ -c version3.cpp

clean:
	rm -f iimage.bin dimage.bin snapshot.rpt error_dump.rpt message.rpt single_cycle version3.o


